name: Deploy .NET 10 App

on:
  push:
    branches: [ master ] # At2aked en esm el branch 3andak master

permissions:
  contents: write

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET 10
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.x'

    - name: Publish
      run: |
        dotnet publish FloosyWeb/FloosyWeb.csproj -c Release -o release --nologo
        # Dah malaf mohem le GitHub Pages 3ashan mayshelsh folderat el framework
        touch release/wwwroot/.nojekyll

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: release/wwwroot